const foilColors = {
  name: 'Foil Colors',
  infoFile: '/stores/html/global/includes/foilColors.html',
  addCost: 'true',
  addCostValue: null,
  swatches: [
    {
      name: 'Gold Foil',
      type: 'standard',
      cmyk: [0, 20, 50, 30],
      rgb: [189, 158, 106],
      spot: 'PANTONE 874 C',
      family: 'Brown',
      foilColor: 'Gold',
      gradientColors:
        'rgb(189, 155, 58) 10%, rgb(230, 199, 101) 35%, rgb(241, 226, 140) 50%, rgb(241, 226, 140) 70%, rgb(230, 199, 101) 85%, rgb(189, 155, 58) 100%',
      category: 'foil',
      availableInDS: true,
    },
    {
      name: 'Silver Foil',
      type: 'standard',
      cmyk: [0, 0, 0, 40],
      rgb: [171, 171, 171],
      spot: 'PANTONE 877 C',
      family: 'Gray',
      foilColor: 'Silver',
      gradientColors:
        'rgb(187, 187, 187) 10%, rgb(224, 224, 224) 35%, rgb(238, 238, 238) 50%, rgb(238, 238, 238) 70%, rgb(224, 224, 224) 85%, rgb(187, 187, 187) 100%',
      category: 'foil',
      availableInDS: true,
    },
    {
      name: 'Rose Gold Foil',
      type: 'standard',
      cmyk: [35, 44, 42, 13],
      rgb: [155, 129, 123],
      spot: 'PANTONE 8041 C',
      family: 'Pink',
      foilColor: 'Rose Gold',
      gradientColors:
        'rgb(219, 159, 144) 10%, rgb(236, 192, 176) 35%, rgb(243, 222, 204) 50%, rgb(243, 222, 204) 70%, rgb(236, 192, 176) 85%, rgb(219, 159, 144) 100%',
      category: 'foil',
      availableInDS: true,
    },
    {
      name: 'Copper Foil',
      type: 'standard',
      cmyk: [30, 50, 85, 0],
      rgb: [187, 135, 63],
      spot: 'PANTONE 876 C',
      family: 'Brown',
      foilColor: 'Copper',
      gradientColors:
        'rgb(194, 122, 61) 10%, rgb(225, 162, 100) 35%, rgb(240, 196, 141) 50%, rgb(240, 196, 141) 70%, rgb(225, 162, 100) 85%, rgb(194, 122, 61) 100%',
      category: 'foil',
      availableInDS: true,
    },
    {
      name: 'Red Foil',
      type: 'standard',
      cmyk: [18, 78, 97, 8],
      rgb: [188, 78, 33],
      spot: 'PANTONE 8923 C',
      family: 'Red',
      foilColor: 'Red',
      gradientColors:
        'rgb(150, 62, 26) 10%, rgb(188, 78, 33) 35%, rgb(249, 125, 74) 50%, rgb(249, 125, 74) 70%, rgb(188, 78, 33) 85%, rgb(150, 62, 26) 100%',
      category: 'foil',
    },
    {
      name: 'Blue Foil',
      type: 'standard',
      cmyk: [90, 70, 14, 2],
      rgb: [44, 81, 140],
      spot: 'PANTONE 8185 C',
      family: 'Blue',
      foilColor: 'Blue',
      gradientColors:
        'rgb(31, 57, 99) 10%, rgb(44, 81, 140) 35%, rgb(62, 117, 204) 50%, rgb(62, 117, 204) 70%, rgb(44, 81, 140) 85%, rgb(31, 57, 99) 100%',
      category: 'foil',
    },
  ],
};

const transparentColor = {
  name: 'None',
  infoFile: null,
  addCost: 'false',
  addCostValue: null,
  swatches: [
    {
      name: 'None',
      type: 'standard',
      cmyk: [null, null, null, null],
      rgb: [null, null, null],
      availableInDS: true,
    },
  ],
};

const standardColors = {
  name: 'Standard Colors',
  swatches: [
    {
      name: 'Gray',
      type: 'standard',
      cmyk: [0, 0, 0, 50],
      rgb: [150, 152, 152],
      family: 'Gray',
      category: 'standard',
    },
    {
      name: 'Charcoal',
      type: 'standard',
      cmyk: [0, 0, 0, 65],
      rgb: [118, 120, 120],
      family: 'Gray',
      category: 'standard',
    },
    {
      name: 'Steel',
      type: 'standard',
      cmyk: [0, 0, 0, 85],
      rgb: [71, 72, 71],
      family: 'Gray',
      category: 'standard',
    },
    {
      name: 'Black',
      type: 'standard',
      cmyk: [0, 0, 0, 100],
      rgb: [28, 27, 26],
      family: 'Black',
      category: 'standard',
    },

    {
      name: 'White',
      type: 'standard',
      cmyk: [0, 0, 0, 0],
      rgb: [255, 255, 255],
      family: 'White',
      category: 'standard',
    },
    {
      name: 'Winter White',
      type: 'standard',
      cmyk: [0, 0, 0, 10],
      rgb: [233, 234, 234],
      family: 'Gray',
      category: 'standard',
    },
    {
      name: 'Matte Silver',
      type: 'standard',
      cmyk: [0, 0, 0, 20],
      rgb: [212, 213, 213],
      family: 'Gray',
      category: 'standard',
    },
    {
      name: 'Platinum',
      type: 'standard',
      cmyk: [0, 0, 0, 30],
      rgb: [191, 192, 193],
      family: 'Gray',
      category: 'standard',
    },

    {
      name: 'Greige',
      type: 'standard',
      cmyk: [17, 17, 22, 0],
      rgb: [216, 205, 193],
      family: 'Neutral',
      category: 'standard',
    },
    {
      name: 'Ashwood',
      type: 'standard',
      cmyk: [1, 14, 22, 38],
      rgb: [172, 155, 137],
      family: 'Brown',
      category: 'standard',
    },
    {
      name: 'Latte',
      type: 'standard',
      cmyk: [0, 25, 38, 60],
      rgb: [127, 104, 82],
      family: 'Brown',
      category: 'standard',
    },
    {
      name: 'Java Bean',
      type: 'standard',
      cmyk: [44, 64, 73, 39],
      rgb: [109, 74, 57],
      family: 'Brown',
      category: 'standard',
    },

    {
      name: 'Lace',
      type: 'standard',
      cmyk: [0, 6, 3, 0],
      rgb: [254, 243, 243],
      family: 'Pink',
      category: 'standard',
    },
    {
      name: 'Spun Sugar',
      type: 'standard',
      cmyk: [3, 18, 18, 0],
      rgb: [246, 215, 200],
      family: 'Pink',
      category: 'standard',
    },
    {
      name: 'Cashmere',
      type: 'standard',
      cmyk: [21, 51, 54, 1],
      rgb: [203, 139, 113],
      family: 'Brown',
      category: 'standard',
    },
    {
      name: 'Berry Rose',
      type: 'standard',
      cmyk: [22, 67, 55, 4],
      rgb: [194, 106, 98],
      family: 'Brown',
      category: 'standard',
    },

    {
      name: 'Terracotta',
      type: 'standard',
      cmyk: [17, 62, 73, 3],
      rgb: [202, 117, 81],
      family: 'Pink',
      category: 'standard',
    },
    {
      name: 'Dark Rose',
      type: 'standard',
      cmyk: [15, 75, 53, 15],
      rgb: [184, 83, 58],
      family: 'Pink',
      category: 'standard',
    },
    {
      name: 'Crab Apple',
      type: 'standard',
      cmyk: [31, 89, 68, 28],
      rgb: [139, 50, 56],
      family: 'Pink',
      category: 'standard',
    },
    {
      name: 'Merlot',
      type: 'standard',
      cmyk: [36, 85, 77, 49],
      rgb: [104, 44, 38],
      family: 'Pink',
      category: 'standard',
    },

    {
      name: 'Soft Blush',
      type: 'standard',
      cmyk: [2, 16, 9, 0],
      rgb: [248, 221, 219],
      family: 'Pink',
      category: 'standard',
    },
    {
      name: 'Pinot Noir',
      type: 'standard',
      cmyk: [12, 36, 20, 0],
      rgb: [223, 174, 178],
      family: 'Pink',
      category: 'standard',
    },
    {
      name: 'Ash Rose',
      type: 'standard',
      cmyk: [27, 48, 39, 1],
      rgb: [191, 143, 138],
      family: 'Pink',
      category: 'standard',
    },
    {
      name: 'Mauve Taupe',
      type: 'standard',
      cmyk: [41, 73, 44, 15],
      rgb: [144, 82, 99],
      family: 'Purple',
      category: 'standard',
    },

    {
      name: 'Warm Orchid',
      type: 'standard',
      cmyk: [11, 27, 4, 0],
      rgb: [225, 193, 214],
      family: 'Purple',
      category: 'standard',
    },
    {
      name: 'Sweet Azalea',
      type: 'standard',
      cmyk: [22, 58, 8, 0],
      rgb: [200, 128, 170],
      family: 'Purple',
      category: 'standard',
    },
    {
      name: 'Boysenberry',
      type: 'standard',
      cmyk: [42, 84, 28, 5],
      rgb: [155, 68, 114],
      family: 'Purple',
      category: 'standard',
    },
    {
      name: 'Sangria',
      type: 'standard',
      cmyk: [30, 100, 10, 40],
      rgb: [123, 21, 82],
      family: 'Purple',
      category: 'standard',
    },

    {
      name: 'Orchid Ice',
      type: 'standard',
      cmyk: [7, 11, 4, 0],
      rgb: [237, 227, 233],
      family: 'Purple',
      category: 'standard',
    },
    {
      name: 'Iris Mauve',
      type: 'standard',
      cmyk: [21, 41, 18, 0],
      rgb: [204, 160, 175],
      family: 'Purple',
      category: 'standard',
    },
    {
      name: 'Mulberry',
      type: 'standard',
      cmyk: [38, 68, 20, 9],
      rgb: [157, 96, 133],
      family: 'Purple',
      category: 'standard',
    },
    {
      name: 'Grape Juice',
      type: 'standard',
      cmyk: [58, 88, 40, 29],
      rgb: [102, 50, 81],
      family: 'Purple',
      category: 'standard',
    },

    {
      name: 'Lavender',
      type: 'standard',
      cmyk: [12, 20, 0, 0],
      rgb: [223, 206, 229],
      family: 'Purple',
      category: 'standard',
    },
    {
      name: 'Sugared Plum',
      type: 'standard',
      cmyk: [20, 35, 0, 0],
      rgb: [205, 173, 209],
      family: 'Purple',
      category: 'standard',
    },
    {
      name: 'Amethyst',
      type: 'standard',
      cmyk: [38, 55, 0, 0],
      rgb: [168, 127, 182],
      family: 'Purple',
      category: 'standard',
    },
    {
      name: 'Plum',
      type: 'standard',
      cmyk: [75, 100, 7, 0],
      rgb: [99, 45, 126],
      family: 'Purple',
      category: 'standard',
    },

    {
      name: 'Lilac Mist',
      type: 'standard',
      cmyk: [20, 13, 4, 0],
      rgb: [207, 212, 229],
      family: 'Purple',
      category: 'standard',
    },
    {
      name: 'Purple Ash',
      type: 'standard',
      cmyk: [46, 33, 18, 0],
      rgb: [150, 159, 181],
      family: 'Purple',
      category: 'standard',
    },
    {
      name: 'Frosty Grape',
      type: 'standard',
      cmyk: [70, 60, 4, 1],
      rgb: [98, 105, 167],
      family: 'Purple',
      category: 'standard',
    },
    {
      name: 'Cool Indigo',
      type: 'standard',
      cmyk: [99, 96, 3, 0],
      rgb: [37, 50, 132],
      family: 'Purple',
      category: 'standard',
    },

    {
      name: 'Icy Blue',
      type: 'standard',
      cmyk: [20, 2, 0, 0],
      rgb: [207, 231, 249],
      family: 'Blue',
      category: 'standard',
    },
    {
      name: 'Blue Lagoon',
      type: 'standard',
      cmyk: [43, 15, 0, 0],
      rgb: [151, 189, 229],
      family: 'Blue',
      category: 'standard',
    },
    {
      name: 'Azure',
      type: 'standard',
      cmyk: [66, 27, 0, 0],
      rgb: [90, 154, 210],
      family: 'Blue',
      category: 'standard',
    },
    {
      name: 'Navy',
      type: 'standard',
      cmyk: [97, 47, 0, 60],
      rgb: [0, 55, 95],
      family: 'Blue',
      category: 'standard',
    },

    {
      name: 'Blue Fog',
      type: 'standard',
      cmyk: [10, 3, 1, 3],
      rgb: [225, 233, 242],
      family: 'Blue',
      category: 'standard',
    },
    {
      name: 'Antique Blue',
      type: 'standard',
      cmyk: [46, 24, 20, 0],
      rgb: [149, 172, 186],
      family: 'Blue',
      category: 'standard',
    },
    {
      name: 'Lakeshore',
      type: 'standard',
      cmyk: [76, 36, 24, 1],
      rgb: [65, 133, 164],
      family: 'Blue',
      category: 'standard',
    },
    {
      name: 'Denim',
      type: 'standard',
      cmyk: [100, 50, 0, 25],
      rgb: [0, 82, 142],
      family: 'Blue',
      category: 'standard',
    },

    {
      name: 'Rainy Day',
      type: 'standard',
      cmyk: [17, 5, 8, 0],
      rgb: [215, 228, 231],
      family: 'Blue',
      category: 'standard',
    },
    {
      name: 'Glacier',
      type: 'standard',
      cmyk: [45, 17, 25, 0],
      rgb: [151, 183, 185],
      family: 'Blue',
      category: 'standard',
    },
    {
      name: 'Blue Spruce',
      type: 'standard',
      cmyk: [72, 32, 43, 5],
      rgb: [78, 136, 138],
      family: 'Blue',
      category: 'standard',
    },
    {
      name: 'Stone Blue',
      type: 'standard',
      cmyk: [82, 57, 41, 19],
      rgb: [57, 88, 109],
      family: 'Blue',
      category: 'standard',
    },

    {
      name: 'Serene Sky',
      type: 'standard',
      cmyk: [20, 0, 7, 0],
      rgb: [208, 233, 238],
      family: 'Teal',
      category: 'standard',
    },
    {
      name: 'Turquoise',
      type: 'standard',
      cmyk: [52, 0, 18, 0],
      rgb: [124, 202, 209],
      family: 'Teal',
      category: 'standard',
    },
    {
      name: 'Jewel Blue',
      type: 'standard',
      cmyk: [76, 12, 26, 0],
      rgb: [18, 164, 181],
      family: 'Teal',
      category: 'standard',
    },
    {
      name: 'Teal Waters',
      type: 'standard',
      cmyk: [87, 13, 27, 35],
      rgb: [0, 110, 128],
      family: 'Teal',
      category: 'standard',
    },

    {
      name: 'Waterfall',
      type: 'standard',
      cmyk: [30, 2, 20, 0],
      rgb: [185, 219, 208],
      family: 'Teal',
      category: 'standard',
    },
    {
      name: 'Sea Glass',
      type: 'standard',
      cmyk: [65, 6, 34, 0],
      rgb: [86, 181, 175],
      family: 'Teal',
      category: 'standard',
    },
    {
      name: 'Malachite',
      type: 'standard',
      cmyk: [85, 26, 54, 6],
      rgb: [0, 132, 123],
      family: 'Teal',
      category: 'standard',
    },
    {
      name: 'Emerald Sea',
      type: 'standard',
      cmyk: [89, 40, 60, 23],
      rgb: [6, 98, 94],
      family: 'Teal',
      category: 'standard',
    },

    {
      name: 'Silvery Sage',
      type: 'standard',
      cmyk: [12, 4, 9, 0],
      rgb: [227, 234, 231],
      family: 'Green',
      category: 'standard',
    },
    {
      name: 'Antique Sage',
      type: 'standard',
      cmyk: [23, 9, 17, 0],
      rgb: [202, 214, 209],
      family: 'Green',
      category: 'standard',
    },
    {
      name: 'Green Willow',
      type: 'standard',
      cmyk: [49, 30, 49, 3],
      rgb: [143, 155, 134],
      family: 'Green',
      category: 'standard',
    },
    {
      name: 'Cactus',
      type: 'standard',
      cmyk: [64, 39, 65, 19],
      rgb: [95, 115, 92],
      family: 'Green',
      category: 'standard',
    },

    {
      name: 'Mint',
      type: 'standard',
      cmyk: [11, 0, 16, 1],
      rgb: [229, 239, 219],
      family: 'Green',
      category: 'standard',
    },
    {
      name: 'Celadon',
      type: 'standard',
      cmyk: [27, 0, 23, 0],
      rgb: [193, 224, 205],
      family: 'Green',
      category: 'standard',
    },
    {
      name: 'Warm Mint',
      type: 'standard',
      cmyk: [57, 0, 53, 0],
      rgb: [116, 193, 146],
      family: 'Green',
      category: 'standard',
    },
    {
      name: 'Parakeet',
      type: 'standard',
      cmyk: [87, 0, 83, 10],
      rgb: [0, 150, 85],
      family: 'Green',
      category: 'standard',
    },

    {
      name: 'Pistachio',
      type: 'standard',
      cmyk: [22, 3, 30, 0],
      rgb: [207, 223, 190],
      family: 'Green',
      category: 'standard',
    },
    {
      name: 'Green Pear',
      type: 'standard',
      cmyk: [46, 9, 67, 0],
      rgb: [152, 189, 115],
      family: 'Green',
      category: 'standard',
    },
    {
      name: 'Clover Green',
      type: 'standard',
      cmyk: [71, 34, 95, 21],
      rgb: [75, 113, 53],
      family: 'Green',
      category: 'standard',
    },
    {
      name: 'Evergreen',
      type: 'standard',
      cmyk: [88, 40, 100, 41],
      rgb: [17, 80, 42],
      family: 'Green',
      category: 'standard',
    },

    {
      name: 'Icy Moss',
      type: 'standard',
      cmyk: [9, 5, 11, 0],
      rgb: [234, 235, 226],
      family: 'Green',
      category: 'standard',
    },
    {
      name: 'Sea Mist',
      type: 'standard',
      cmyk: [28, 15, 37, 0],
      rgb: [192, 198, 168],
      family: 'Green',
      category: 'standard',
    },
    {
      name: 'Lily Pad',
      type: 'standard',
      cmyk: [47, 29, 61, 4],
      rgb: [147, 155, 114],
      family: 'Green',
      category: 'standard',
    },
    {
      name: 'Ivy Green',
      type: 'standard',
      cmyk: [62, 45, 73, 30],
      rgb: [90, 98, 71],
      family: 'Green',
      category: 'standard',
    },

    {
      name: 'Ivory',
      type: 'standard',
      cmyk: [0, 0, 7, 2],
      rgb: [252, 249, 237],
      family: 'Neutral',
      category: 'standard',
    },
    {
      name: 'Champagne',
      type: 'standard',
      cmyk: [6, 9, 19, 0],
      rgb: [242, 229, 207],
      family: 'Neutral',
      category: 'standard',
    },
    {
      name: 'Matte Gold',
      type: 'standard',
      cmyk: [0, 13, 45, 15],
      rgb: [223, 195, 135],
      family: 'Yellow',
      category: 'standard',
    },
    {
      name: 'Butter Pecan',
      type: 'standard',
      cmyk: [26, 49, 92, 7],
      rgb: [183, 130, 46],
      family: 'Yellow',
      category: 'standard',
    },

    {
      name: 'Lemonade',
      type: 'standard',
      cmyk: [0, 2, 16, 0],
      rgb: [255, 248, 220],
      family: 'Yellow',
      category: 'standard',
    },
    {
      name: 'Blonde',
      type: 'standard',
      cmyk: [0, 5, 45, 0],
      rgb: [255, 237, 158],
      family: 'Yellow',
      category: 'standard',
    },
    {
      name: 'Pineapple',
      type: 'standard',
      cmyk: [1, 13, 97, 0],
      rgb: [255, 213, 0],
      family: 'Yellow',
      category: 'standard',
    },
    {
      name: 'Honey',
      type: 'standard',
      cmyk: [8, 27, 81, 0],
      rgb: [236, 186, 66],
      family: 'Yellow',
      category: 'standard',
    },

    {
      name: 'Parchment',
      type: 'standard',
      cmyk: [5, 13, 16, 0],
      rgb: [243, 223, 208],
      family: 'Neutral',
      category: 'standard',
    },
    {
      name: 'Hazelnut',
      type: 'standard',
      cmyk: [12, 28, 39, 0],
      rgb: [226, 187, 154],
      family: 'Brown',
      category: 'standard',
    },
    {
      name: 'Ginger',
      type: 'standard',
      cmyk: [19, 49, 71, 2],
      rgb: [206, 141, 86],
      family: 'Brown',
      category: 'standard',
    },
    {
      name: 'Matte Copper',
      type: 'standard',
      cmyk: [27, 62, 89, 13],
      rgb: [170, 103, 48],
      family: 'Brown',
      category: 'standard',
    },

    {
      name: 'Coconut',
      type: 'standard',
      cmyk: [1, 7, 8, 0],
      rgb: [252, 239, 231],
      family: 'Neutral',
      category: 'standard',
    },
    {
      name: 'Peach',
      type: 'standard',
      cmyk: [0, 21, 28, 0],
      rgb: [253, 210, 179],
      family: 'Orange',
      category: 'standard',
    },
    {
      name: 'Papaya',
      type: 'standard',
      cmyk: [2, 56, 85, 0],
      rgb: [239, 135, 50],
      family: 'Orange',
      category: 'standard',
    },
    {
      name: 'Pumpkin',
      type: 'standard',
      cmyk: [0, 76, 100, 15],
      rgb: [205, 80, 14],
      family: 'Orange',
      category: 'standard',
    },

    {
      name: 'Light Salmon',
      type: 'standard',
      cmyk: [0, 27, 18, 0],
      rgb: [250, 200, 191],
      family: 'Orange',
      category: 'standard',
    },
    {
      name: 'Coral',
      type: 'standard',
      cmyk: [0, 54, 45, 0],
      rgb: [244, 144, 123],
      family: 'Orange',
      category: 'standard',
    },
    {
      name: 'Nutmeg',
      type: 'standard',
      cmyk: [27, 74, 78, 17],
      rgb: [162, 81, 58],
      family: 'Orange',
      category: 'standard',
    },
    {
      name: 'Chestnut',
      type: 'standard',
      cmyk: [24, 95, 100, 19],
      rgb: [159, 43, 27],
      family: 'Red',
      category: 'standard',
    },

    {
      name: 'Pink Divinity',
      type: 'standard',
      cmyk: [0, 15, 4, 0],
      rgb: [252, 225, 230],
      family: 'Pink',
      category: 'standard',
    },
    {
      name: 'Baby Pink',
      type: 'standard',
      cmyk: [0, 38, 15, 0],
      rgb: [247, 178, 184],
      family: 'Pink',
      category: 'standard',
    },
    {
      name: 'Punch',
      type: 'standard',
      cmyk: [9, 81, 47, 0],
      rgb: [220, 79, 98],
      family: 'Pink',
      category: 'standard',
    },
    {
      name: 'Ruby Red',
      type: 'standard',
      cmyk: [0, 100, 82, 32],
      rgb: [169, 20, 31],
      family: 'Red',
      category: 'standard',
    },

    {
      name: 'Light Chiffon',
      type: 'standard',
      cmyk: [0, 7, 2, 0],
      rgb: [254, 241, 243],
      family: 'Pink',
      category: 'standard',
    },
    {
      name: 'Pink Glass',
      type: 'standard',
      cmyk: [3, 23, 11, 0],
      rgb: [244, 206, 207],
      family: 'Pink',
      category: 'standard',
    },
    {
      name: 'Watermelon',
      type: 'standard',
      cmyk: [0, 68, 23, 0],
      rgb: [240, 113, 138],
      family: 'Pink',
      category: 'standard',
    },
    {
      name: 'Berry Pink',
      type: 'standard',
      cmyk: [6, 91, 53, 16],
      rgb: [192, 48, 72],
      family: 'Pink',
      category: 'standard',
    },
  ],
};

export { foilColors, standardColors, transparentColor };
